// app/head.tsx

export default function Head() {
    return (
      <>
        <title>AIMedia Om</title>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.png" sizes="32x32" type="image/png" />
      </>
    );
  }
  