import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Locale } from "@/i18n.config";
import { Directions, Languages } from "@/components/constants/enum";
import Header from "@/components/header";

const robote = Roboto({
  subsets: ["latin"],

  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "AIMedia Om",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;
  
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={robote.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
