import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Locale } from "@/i18n.config";
import { Directions, Languages } from "@/components/constants/enum";
import Header from "@/components/header";

const robote = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "AIMedia Om",
  description: "Generated by create next app",
};

// أضف هذا لتعطيل التخزين المؤقت
export const dynamic = 'force-dynamic';

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const local = params.locale; // تم تعديل هذه السطر
  
  console.log('Current locale:', local); // للتأكد من قيمة locale
  
  return (
    <html
      lang={local}
      dir={local === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={robote.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}